name: Build Scala

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-scala:
    name: Build Scala
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Download dependencies
        run: npm ci

      - name: Npm Build
        run: npm run build --if-present

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'

      - name: Compile Morphir implementation
        run: mvn -B -ntp clean package
